---
title: "Comparision of ranks with enrichment analysis"
output: html_notebook
---

Using the enrichment analysis to compare the rankings and metricsf

```{r}
#install.packages("rlist")
library(rlist)
library(ggplot2)
library(latex2exp)
library(systemPipeR)

setwd("~/Dropbox/PNNL/Omics/SARS-COV-2/SARSCov2/")
source("GeneSets.R")

# get the background gene set/list
biggerTransGeneSet <- as.character(read.table("biggerTransGenes.txt",  header = FALSE, sep = "")$V1)
bigTransGeneSet <- as.character(read.table("bigTransGenes.txt",  header = FALSE, sep = "")$V1)
bakgrdGeneList <- bigTransGeneSet
lenBakgrd <- length(bakgrdGeneList)
#
# sars1Targets <- as.character(read.table("sars1-targets.txt", header = FALSE, sep = "")$V1)
# sars2Targets <- as.character(read.table("sars1-targets.txt", header = FALSE, sep = "")$V1)
# sarsTargets <- as.character(read.table("sars-targets.txt", header = FALSE, sep = "")$V1)

```

## Functions for calculating the enrichment scores (using p = 0, which is equavalent to Kolomogrov-Smirnov statistics)

```{r}
esFn <- function(x, p = 1) {
  len = length(x)
  miss = ifelse(x!=0, 0, 1)
  #hiti = ((miss * 2 - 1) - miss) / 2
  if (p == 0) {
    xp <- ifelse(x!=0, 1, 0)
  } else {
    xp = abs(x)**p
  }
  sumxp = sum(xp)
  summiss = sum(miss)
  if (sumxp == 0) {
    hitp = rep(0, len)
  } else {
    hitp = cumsum(xp) / sumxp
  }
  if (summiss == 0) {
    missp = rep(0, len)
  } else {
    missp = cumsum(miss) / summiss
  }
  maximum = max(hitp - missp)
  minimum = min(hitp - missp)
  score = ifelse(abs(maximum) > abs(minimum), maximum, minimum)
  return(score)
}

library(MASS)
epFn <- function(x, xnull) {
  fit <- fitdistr(xnull[xnull > 0], densfun="normal")
  pvalue = 1 - pnorm(abs((x - fit$estimate[1]) / (fit$estimate[2])))
  return(pvalue)
}
```


Use the list of gene to do enrichment analysis

```{r}
samplesize = 1000
targetSetNames <- c("sars1", "sars", "influenza", "influenzaIntersect", "influenzaAll", "ebola", "ebolaLong")
centralities <- c("s-closeness", "s-betweenness")
rankMethods <- c("Number of Increases", "Euclidean Distance", "Absolute Rank Change", "Relative Rank Change", "Absolute Change", "Relative Change", "Combined Score")
# rankMethods <- c("Number.of.Increases", "Euclidean.Distance", "Absolute.Rank.Change", "Relative.Rank.Change", "Absolute.Change", "Relative.Change", "Combined.Score")
virusNames <- c("Sars", "Mers", "Iv", "Eb")
```


```{r}
dfEnrich <- setNames(data.frame(matrix(ncol = 8, nrow = 0)), c("genecount", "p", "Enrichment score", "p-value", "Rank method", "Virus name", "Target sets","Hypergraph metrics"))
dfi <- 1
```

### analyze the SARS1 targets with all ranks and metrics

```{r}
for (centrality in centralities) {
  for (virusName in virusNames) {
    infile <- sprintf("./no%s-%s_changes.csv", virusName, centrality)
    if (file.exists(infile)) {
      genelist <- read.csv(infile, header = TRUE, row.names = 1)
      colnames(genelist) <- rankMethods
      allGenenames <- rownames(genelist)
      lenAll <- length(allGenenames)
      
      for (rankMethod in rankMethods) {
        rankOri <- as.matrix(genelist[order(-genelist[rankMethod]),][rankMethod])
        rank <- subset(rankOri, is.finite(rankOri))
        genenames <- rownames(rank)
        
        for (targetSetName in targetSetNames) {
          targetSet <- as.character(read.table(paste0(targetSetName,"-targets.txt"), header = FALSE, sep = "")$V1)
          enr <- enrichment_by_fishers(genenames, bakgrdGeneList, targetSet)
          p = enr$fisher$p.value
          f = enr$foldx
          mat = enr$mat
          lenShort <- length(genenames)
          zscores <- rank
          zscores[which(!(genenames %in% targetSet))] <- 0
          es <- esFn(zscores)
          sampledValues = c()
          for (k in 1:samplesize) {
            sampledis = sample(1:lenBakgrd)
            tempGenenames <- genenames[sampledis[1:lenShort]]
            tempZscores <- zscores[sampledis[1:lenShort]]
            tempZscores[which(!(tempGenenames %in% targetSet))] <- 0
            sampledValues = c(sampledValues, esFn(tempZscores))
          }
          ep = (length(which(sampledValues >= es)) + 1) / (samplesize + 1)
          #ep = epFn(es, sampledValues)
          # save test result
          dfEnrich[dfi,] <- c(mat[1,1], p, es, ep, rankMethod, virusName, targetSetName, centrality)
          dfi <- dfi + 1
        }
      }
    }
  }
}
```


```{r}
for (centrality in centralities) {
  rankMethod <- "individual"
  infile <- sprintf("./bigTrans-%s-%s-ranks.csv", centrality, rankMethod)
  if (file.exists(infile)) {
    genelist <- read.csv(infile, header = TRUE, row.names = 1)
    allGenenames <- rownames(genelist)
    lenAll <- length(allGenenames)
    for (virusName in virusNames) {
      rankOri <- as.matrix(genelist[order(-genelist[virusName]),][virusName])
      rank <- subset(rankOri, is.finite(rankOri))
      genenames <- rownames(rank)
      for (targetSetName in targetSetNames) {
        targetSet <- as.character(read.table(paste0(targetSetName,"-targets.txt"), header = FALSE, sep = "")$V1)
        enr <- enrichment_by_fishers(genenames, bakgrdGeneList, targetSet)
        p = enr$fisher$p.value
        f = enr$foldx
        mat = enr$mat
        lenShort <- length(genenames)
        zscores <- rank
        zscores[which(!(genenames %in% targetSet))] <- 0
        es <- esFn(zscores)
        sampledValues = c()
        for (k in 1:samplesize) {
          sampledis = sample(1:lenBakgrd)
          tempGenenames <- genenames[sampledis[1:lenShort]]
          tempZscores <- zscores[sampledis[1:lenShort]]
          tempZscores[which(!(tempGenenames %in% targetSet))] <- 0
          sampledValues = c(sampledValues, esFn(tempZscores))
        }
        ep = (length(which(sampledValues >= es)) + 1) / (samplesize + 1)
        #ep = epFn(es, sampledValues)
        # save test result
        dfEnrich[dfi,] <- c(mat[1,1], p, es, ep, rankMethod, virusName, targetSetName, centrality)
        dfi <- dfi + 1
      }
    }
  }
}

```

```{r}
save(dfEnrich, file = "dfEnrich.RData")
```


```{r}
load("dfEnrich.RData")
```

```{r}
dfEnrich$`Enrichment score` <- as.numeric(dfEnrich$`Enrichment score`)
dfEnrich$`p-value` <- as.numeric(dfEnrich$`p-value`)
```

```{r}
# df <- dfEnrich[Reduce(intersect, list(which(dfEnrich$`Target sets` == "sars1"), which(), which(), which())),]
df <- dfEnrich[dfEnrich$`Target sets` == "sars1",]
ggplot(data = df, mapping = aes(x=`Rank method`, y=`Enrichment score`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_continuous() + theme(axis.text.x = element_text(angle=270))
```

```{r}
ggplot(data = df, mapping = aes(x=`Rank method`, y=`p-value`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_log10() + theme(axis.text.x = element_text(angle=270))
```



```{r}
# df <- dfEnrich[Reduce(intersect, list(which(dfEnrich$`Target sets` == "sars1"), which(), which(), which())),]
df <- dfEnrich[dfEnrich$`Target sets` == "influenza",]
ggplot(data = df, mapping = aes(x=`Rank method`, y=`Enrichment score`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_continuous() + theme(axis.text.x = element_text(angle=270))
```


```{r}
ggplot(data = df, mapping = aes(x=`Rank method`, y=`p-value`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_log10() + theme(axis.text.x = element_text(angle=270))
```



```{r}
# df <- dfEnrich[Reduce(intersect, list(which(dfEnrich$`Target sets` == "sars1"), which(), which(), which())),]
df <- dfEnrich[dfEnrich$`Target sets` == "influenzaRNAi1",]
ggplot(data = df, mapping = aes(x=`Rank method`, y=`Enrichment score`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_continuous() + theme(axis.text.x = element_text(angle=270))
```


```{r}
ggplot(data = df, mapping = aes(x=`Rank method`, y=`p-value`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_log10() + theme(axis.text.x = element_text(angle=270))
```



```{r}
# df <- dfEnrich[Reduce(intersect, list(which(dfEnrich$`Target sets` == "sars1"), which(), which(), which())),]
df <- dfEnrich[dfEnrich$`Target sets` == "influenzaAll",]
ggplot(data = df, mapping = aes(x=`Rank method`, y=`Enrichment score`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_continuous() + theme(axis.text.x = element_text(angle=270))
```


```{r}
ggplot(data = df, mapping = aes(x=`Rank method`, y=`p-value`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_log10() + theme(axis.text.x = element_text(angle=270))
```


```{r}
# df <- dfEnrich[Reduce(intersect, list(which(dfEnrich$`Target sets` == "sars1"), which(), which(), which())),]
df <- dfEnrich[dfEnrich$`Target sets` == "ebola",]
ggplot(data = df, mapping = aes(x=`Rank method`, y=`Enrichment score`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_continuous() + theme(axis.text.x = element_text(angle=270))
```


```{r}
ggplot(data = df, mapping = aes(x=`Rank method`, y=`p-value`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_log10() + theme(axis.text.x = element_text(angle=270))
```


```{r}
# df <- dfEnrich[Reduce(intersect, list(which(dfEnrich$`Target sets` == "sars1"), which(), which(), which())),]
df <- dfEnrich[dfEnrich$`Target sets` == "ebolaLong",]
ggplot(data = df, mapping = aes(x=`Rank method`, y=`Enrichment score`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_continuous() + theme(axis.text.x = element_text(angle=270))
```


```{r}
ggplot(data = df, mapping = aes(x=`Rank method`, y=`p-value`, color = `Virus name`, shape = `Hypergraph metrics`)) + geom_point(size=3 ,alpha = 0.6) + geom_line(linetype = "dashed") + scale_y_log10() + theme(axis.text.x = element_text(angle=270))
```

# Comparing the targeted lists

```{r}
targetSetNames0 <- targetSetNames <- c("sars1", "sars2", "influenza", "ebola")
targetSets <- list()
for (i in seq(length(targetSetNames0))) {
  targetSet <- as.character(read.table(paste0(targetSetNames0[i],"-targets.txt"), header = FALSE, sep = "")$V1)
  targetSets[[i]] <- targetSet
}

names(targetSets) <- targetSetNames0

```

```{r}
vennset <- overLapper(targetSets, type="vennsets")
vennPlot(vennset, mymain = "Intersections of target genes")
```


```{r}
vennFile <- paste0("vennDiagram.pdf")
pdf(vennFile,height=6,width=8)
vennPlot(vennset, mymain = "Intersections of target genes")
dev.off()
```

```{r}
interList <- vennlist(vennset)
save(interList, file = "intersections.RData")
```

```{r}
interNames <- names(interList)
for (i in seq(length(interNames))) {
  interName <- interNames[i]
  intergenes <- interList[[i]]
  if (length(intergenes) > 0) {
    write.table(intergenes, file = paste0("targetSets/intersections-", interName, ".txt"), sep="\t", quote=FALSE, col.names = FALSE)
  }
}
```

```{r}
topNum <- 1000
```


```{r}
for (rankMethod in rankMethods) {
  
  for (centrality in centralities) {
    
    targetSets <- list()
    for (i in seq(length(virusNames))) {
      infile <- sprintf("./no%s-%s_changes.csv", virusNames[i], centrality)
      if (file.exists(infile)) {
        genelist <- read.csv(infile, header = TRUE, row.names = 1)
        colnames(genelist) <- rankMethods
        
        rankOri <- as.matrix(genelist[order(-genelist[rankMethod]),][rankMethod])
        rank <- subset(rankOri, is.finite(rankOri))
        genenames <- rownames(rank)
        
        targetSets[[i]] <- genenames[1:topNum]
        
      }
    }
    names(targetSets) <- virusNames
    
    label = paste0(centrality, "-", rankMethod, "-top-", topNum)
    dir.create(file.path("venn", label))
    
    vennset <- overLapper(targetSets, type="vennsets")
    vennFile <- paste0("venn/", label, ".pdf")
    pdf(vennFile,height=6,width=8)
    vennPlot(vennset, mymain = paste0("Intersections of target genes: ", label))
    dev.off()
    
    interList <- vennlist(vennset)
    save(interList, file = paste0("venn/", label, ".RData"))
    
    interNames <- names(interList)
    for (i in seq(length(interNames))) {
      interName <- interNames[i]
      intergenes <- interList[[i]]
      if (length(intergenes) > 0) {
        write.table(intergenes, file = paste0("venn/", label, "/", interName, ".txt"), sep="\t", quote=FALSE, col.names = FALSE, row.names = FALSE)
      }
    }
    
  }
}
```



```{r}
rankMethod <- "individual"

for (centrality in centralities) {
  
  targetSets <- list()
  infile <- sprintf("./bigTrans-%s-%s-ranks.csv", centrality, rankMethod)
  for (i in seq(length(virusNames))) {

    if (file.exists(infile)) {
      genelist <- read.csv(infile, header = TRUE, row.names = 1)
      colnames(genelist) <- virusNames
      
      rankOri <- as.matrix(genelist[order(-genelist[virusNames[i]]),][virusNames[i]])
      rank <- subset(rankOri, is.finite(rankOri))
      genenames <- rownames(rank)
      
      targetSets[[i]] <- genenames[1:topNum]
      
    }
  }
  names(targetSets) <- virusNames
  
  label = paste0(centrality, "-", rankMethod, "-top-", topNum)
  dir.create(file.path("venn", label))
  
  vennset <- overLapper(targetSets, type="vennsets")
  vennFile <- paste0("venn/", label, ".pdf")
  pdf(vennFile,height=6,width=8)
  vennPlot(vennset, mymain = paste0("Intersections of target genes: ", label))
  dev.off()
  
  interList <- vennlist(vennset)
  save(interList, file = paste0("venn/", label, ".RData"))
  
  interNames <- names(interList)
  for (i in seq(length(interNames))) {
    interName <- interNames[i]
    intergenes <- interList[[i]]
    if (length(intergenes) > 0) {
      write.table(intergenes, file = paste0("venn/", label, "/", interName, ".txt"), sep="\t", quote=FALSE, col.names = FALSE, row.names = FALSE)
    }
  }
  
}
```



